.PHONY: clean All

All:
	@echo "----------Building project:[ lab_2_1 - Debug ]----------"
	@cd "lab22" && "$(MAKE)" -f  "lab_2_1.mk" && "$(MAKE)" -f  "lab_2_1.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ lab_2_1 - Debug ]----------"
	@cd "lab22" && "$(MAKE)" -f  "lab_2_1.mk" clean
