.PHONY: clean All

All:
	@echo "----------Building project:[ keypad2 - Debug ]----------"
	@cd "keypad2" && "$(MAKE)" -f  "keypad2.mk" && "$(MAKE)" -f  "keypad2.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ keypad2 - Debug ]----------"
	@cd "keypad2" && "$(MAKE)" -f  "keypad2.mk" clean
